version: "3.7"

networks:
  local:
    name: local
    driver: bridge
    ipam:
      config:
        - subnet: 172.86.1.0/24

volumes:
  bitcoin:
  lnd:
  taro:

services:
  bitcoin:
    image: bitcoin:latest
    restart: unless-stopped
    volumes:
      - bitcoin:/bitcoin/.bitcoin
    networks:
      - local

  lnd:
    image: lnd:latest
    restart: unless-stopped
    volumes:
      - lnd:/lnd/.lnd
    networks:
      - local
    depends_on:
      - bitcoin
    command: >-
      lnd
      --noseedbackup
      --maxpendingchannels=10
      --trickledelay=5000
      --alias=lnd
      --externalip=172.86.1.101
      --tlsextraip=172.86.1.101
      --listen=0.0.0.0:9735
      --rpclisten=0.0.0.0:10009
      --restlisten=0.0.0.0:8080
      --tlsextradomain=lnd
      --bitcoin.active
      --bitcoin.regtest
      --bitcoin.node=bitcoind
      --bitcoind.rpchost=bitcoin:18443
      --bitcoind.rpcuser=lnmarkets
      --bitcoind.rpcpass=lnmarkets
      --bitcoind.zmqpubrawblock=tcp://bitcoin:28334
      --bitcoind.zmqpubrawtx=tcp://bitcoin:28335

  taro:
    image: taro:latest
    restart: unless-stopped
    volumes:
      - lnd:/lnd
      - taro:/taro/.taro
    networks:
      - local
    depends_on:
      - bitcoin
      - lnd
    command: >-
      tarod --network=regtest --debuglevel=debug --lnd.host=lnd:10009 --lnd.macaroonpath=/lnd/data/chain/bitcoin/regtest/admin.macaroon --lnd.tlspath=/lnd/tls.cert
