name: taro

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "taro/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: vafanassieff
          password: ${{ secrets.CR_PAT }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: vafanassieff
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version
        run: |
          echo 'VERSION='$(grep -m 1 'ENV TARO_VERSION=' taro/Dockerfile | cut -f2- -d=) >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: taro
          push: true
          tags: |
            ghcr.io/vafanassieff/taro:latest
            ghcr.io/vafanassieff/taro:${{ env.VERSION }}
            vafanassieff/taro:latest
            vafanassieff/taro:${{ env.VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
